name: "Upload Private Artifacts"
description: "Uploads build artifacts that should not be available for public consumption."
inputs:
  path:
    description: "Directory containing the files to upload"
    required: true
  fileserver_url:
    description: "Server to use for upload"
    required: true
    default: "https://quic-yocto-fileserver-1029608027416.us-central1.run.app"
  upload_threads:
    description: "Number of concurrent upload threads to use"
    required: true
    default: "5"
outputs:
  url:
    description: "URL where objects are availble at"
    value: ${{ steps.upload.outputs.url }}

runs:
  using: docker
  image: Dockerfile
