name: Unit Test

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifacts
        run: |
          set -eux

          mkdir build
          echo 8675309 > build/test-artifact.txt

      - name: Upload artifacts
        uses: qualcomm-linux/upload-private-artifact-action@main
        with:
          path: ./build
          build_id: "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}"
