name: Unit Test

on:
  push:
    branches:
      - main


permissions:
  id-token: write
  security-events: read  # This is required to handle authentication for upload-private-artifact-action

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifacts
        run: |
          set -eux

          mkdir build
          echo 8675309 > build/test-artifact.txt

      - name: Upload artifacts
        uses: qualcomm-linux/upload-private-artifact-action@main
        with:
          path: ./build
          github_token: "${{ secrets.GITHUB_TOKEN }}"
